### ISSUE TITLE
Is this docker support armv8/aarch64?

### ISSUE THREAD

**Issue by LinusJun** [djaydev/docker-glass-isc-dhcp#1]
Is this docker support armv8/aarch64?

**Comment by djaydev** [comment]
You can try to use djaydev/glass-isc-dhcp:arm64v8 .  I don't have a device to test it, not sure if it works or not.

**Comment by LinusJun** [comment]
thanks a lot,I will have a try!

**Comment by LinusJun** [comment]
PERFECT! IT'S WORKING NOW! THANK YOU SO MUCH!
