### ISSUE TITLE
throw new ERR_SOCKET_BAD_PORT(options.port)

### ISSUE THREAD

**Issue by tsvsj** [djaydev/docker-glass-isc-dhcp#2]
Hi,

thanks for your work. Unfortunately I'm continously getting the following error while starting the container:

```
[services.d] stopping services
This is probably not a problem with npm. There is likely additional logging output above.
Failed at the dhcpd-glass@0.0.0 start script.

Exit status 1
dhcpd-glass@0.0.0 start: `node ./bin/www`
1
ELIFECYCLE
    at require (internal/modules/cjs/helpers.js:25:18)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.<anonymous> (/opt/glass-isc-dhcp/app.js:155:14)
    at new WebSocketServer (/opt/glass-isc-dhcp/node_modules/ws/lib/WebSocketServer.js:76:20)
    at Server.listen (net.js:1405:13)
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 2.2222222222222224e+28.

      ^
      throw new ERR_SOCKET_BAD_PORT(options.port);
net.js:1405
[Glass Server] Websocket server starting on port: 2.2222222222222224e+28
[Glass Server] DHCP log watcher initialized
[Glass Server] Config watcher initialized
[Glass Server] Watching leases file '/var/lib/dhcp/dhcpd.leases'

> node ./bin/www
> dhcpd-glass@0.0.0 start /opt/glass-isc-dhcp
```
(in reversed order)

I was trying to change the websocket port. During my attempts I've completely removed the variable, so I'm running on the default port.

Thanks in advance.

**Comment by djaydev** [comment]
Can you please send your complete docker run command that gave that error? thanks

**Comment by djaydev** [comment]
hi @tsvsj 
I did some testing on som other platforms.  Based on that log you sent I believe we should start with you docker run command.  Can you please send the complete docker run command here, including all variables, ports, volumes, and options. thanks.

**Comment by tsvsj** [comment]
hi @djaydev,

I'm sorry, but I didn't get any notification, that there was an update in this issue...

Here is my command:
```
docker run --name=glass-isc-dhcp1 --hostname=glass-isc-dhcp1 \
	--env="TZ=Europe/Berlin" \
	--env="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
	--env="LANG=en_US.UTF-8" \
	--env="S6_BEHAVIOUR_IF_STAGE2_FAILS=3" \
	--env="S6_SERVICE_DEPS=1" \
	--env="USER_ID=1000" \
	--env="GROUP_ID=1000" \
	--env="APP_NAME=DockerApp" \
	--env="APP_USER=app" \
	--env="XDG_DATA_HOME=/config/xdg/data" \
	--env="XDG_CONFIG_HOME=/config/xdg/config" \
	--env="XDG_CACHE_HOME=/config/xdg/cache" \
	--env="XDG_RUNTIME_DIR=/tmp/run/user/app" \
	--env="ADMINPASSWORD=MYPASSWORD" \
   --env="WEBADMINPORT=3000" \
   --volume="<LOCAL PATH>/glass-isc-dhcp/leases:/var/lib/dhcp:rw" \
   --volume="<LOCAL PATH>/glass-isc-dhcp/data:/etc/dhcp:rw" \
   --volume="/config" \
   --network=host 
   --restart=always \
   --detach=true -t djaydev/glass-isc-dhcp:latest /init
```

The command is reverse engineered using runlike. The container was created on a Synology NAS, using the UI.

Thanks. ;-)

**Comment by djaydev** [comment]
No problem.

I run this docker image on a x86 linux server, and a 32bit raspberry Pi.  Unfortunately I don't have any experience with Synology NAS.  

The issue is the definitely the port because of these lines from the logs:

```
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 2.2222222222222224e+28.

      ^
      throw new ERR_SOCKET_BAD_PORT(options.port);
net.js:1405
[Glass Server] Websocket server starting on port: 2.2222222222222224e+28
```

I did some web searching and I think the first thing to try is setting the username and group to:
 set USER_ID to 1024 and GROUP_ID to 100

**Comment by tsvsj** [comment]
Unfortunately that didn't change anything.

I'm not sure if there are any restrictions on the Synology, which may restrict opening port 3000 to the container. The container was created using the host network.

I've now re-created the container using Portainer and MACVLAN. So the container receives an IP address from my LAN. Started the container and now it's up and running. ;-)
If your interested I could do some more testing on the NAS, to help to find the root cause for the issue. The deployment on the Synology NAS Docker UI is much more comfortable than in Portainer, but feature-limited as well.

Cheers

**Comment by djaydev** [comment]
Glad you got it working.  I'm not sure where to even begin with finding the root cause with Synology.  I use host networking on both of my linux servers with the default port and changing it as well.
