### ISSUE TITLE
DHCP server not starting

### ISSUE THREAD

**Issue by nofuturekid** [djaydev/docker-glass-isc-dhcp#3]
I have pulled the latest image and the DHCP server is not starting:

**Container Log:**
    GET /dhcp_start_stop_restart?v_ajax 200 35.928 ms - 2494
    [WS] STATUS: Socket clients (1)
    GET /get_stats 304 38.503 ms - -
    /bin/sh: /usr/sbin/service: not found
    POST /dhcp_start_stop_restart 127 62.679 ms - 109

I guess there is something missing, presumably "/usr/sbin/service".

**Comment by djaydev** [comment]
Please post here your complete docker run command that you used when starting the container.  Also, what platform are you using? x86, arm, etc?

**Comment by nofuturekid** [comment]
Sorry forgot to supply these informations:

It's not my first container running and usually I also build some of my own ;).
On this host there are around 15 containers running...

**Raspberry Pi 4**

**_uname -srvmpio_**

    Linux 4.19.88-v7l+ #1284 SMP Wed Dec 11 13:51:57 GMT 2019 armv7l unknown unknown GNU/Linux

**_docker --version_**

    Docker version 19.03.5, build 633a0ea

**SHA256 of "glass-isc-dhcp:latest"**

    sha256:9f5256535f3add304445390c5358d2e82b5864ceed0d1d2b80c859114265a556

**docker-compose.yaml:**

    version: "3.7"

    x-labels:
      &default-labels
      com.centurylinklabs.watchtower.enable: true

    services:
      ...
      ...
      ...
      isc-dhcp:
        container_name: isc-dhcp
        image: djaydev/glass-isc-dhcp:latest
        restart: unless-stopped
        volumes:
          - ${CONTAINER_ROOT:?err}/isc-dhcp/_data/dhcp:/etc/dhcp
          - ${CONTAINER_ROOT:?err}/isc-dhcp/_data/leases:/var/lib/dhcp
        network_mode: host
        environment:
          - PUID=${PUID:?err}
          - PGID=${PGID:?err}
          - TZ=${TZ:?err}
          - ADMINPASSWORD=${DHCP_WEB_ADMIN_PASSWORD:?err}
          - WEBSOCKETPORT=6464
          - WEBADMINPORT=4000
        labels:
          <<: *default-labels
      ...
      ...
      ...

BTW: Would be a nice feature to have the possibility to change the admin users name too.

**Comment by djaydev** [comment]
No worries! And sorry I don't mean to offend with any questions, just going through the troubleshooting steps since I'm able to download the image and the dhcp server starts successfully.

You're running the armv7 image so I'll focus on that one, I have a raspberry pi to test it on.

In your dhcpd.conf file, there's an error, missing a "." after .168 :
`option domain-name-servers 192.1681.1, 1.1.1.1;`

You can test your config file with alpine docker image:
`docker run --rm -ti -v ${CONTAINER_ROOT:?err}/isc-dhcp/_data/dhcp:/etc/dhcp alpine sh`

then install dhcp server:
`apk update && apk add dhcp`

then start dhcp server, you will get log messages in the terminal with any failures
`/usr/sbin/dhcpd -4 -f -d --no-pid -cf /etc/dhcp/dhcpd.conf`


Again, my apologies if you already know that and/or already have done this

**Comment by nofuturekid** [comment]
I was not offended ^^, impressive support from your side. The missing dot is a solely in the reply here, on the actual file it's correct. (Checked it, twice now)

**Comment by nofuturekid** [comment]
When I connect to the container, I can start the DHCP manually, but it will not come up when the container starts and I'm also not able to start/stop it via the WebGUI (which was my initial complain about)

**Comment by djaydev** [comment]
Let's grab the dhcp log.  Start the container normally and then connect to the console and cat out the /var/log/dhcp.log

```
docker exec -ti isc-dhcp sh
/opt # cat /var/log/dhcp.log
```

**Comment by nofuturekid** [comment]
**Docker log:**

    > dhcpd-glass@0.0.0 start /opt/glass-isc-dhcp
    > node ./bin/www
    [Glass Server] Watching leases file '/var/lib/dhcp/dhcpd.leases'
    [Glass Server] Config watcher initialized
    [Glass Server] DHCP log watcher initialized
    [Glass Server] Websocket server starting on port: 6464
    [Glass Server] Bootup complete
    [Glass Server] Leases file loaded
    [Glass Server] OUI Database Loaded
    GET /api/get_websocket_config 304 23.606 ms - -
    GET /api/get_websocket_config 304 3.561 ms - -
    [WS] CLIENT_CONNECT: Socket clients (1)
    [WS] STATUS: Socket clients (1)
    [WS] CLIENT_CONNECT: Socket clients (2)
    [WS] STATUS: Socket clients (2)

**root@isc-dhcp/_data/dhcp# docker exec -ti isc-dhcp bash**
  bash-5.0# cat /var/log/dhcp.log

    Internet Systems Consortium DHCP Server 4.4.1
    Copyright 2004-2018 Internet Systems Consortium.
    All rights reserved.
    For info, please visit https://www.isc.org/software/dhcp/
    Config file: /etc/dhcp/dhcpd.conf
    Database file: /var/lib/dhcp/dhcpd.leases
    PID file: /run/dhcp/dhcpd.pid
    Wrote 0 leases to leases file.
    
    No subnet declaration for veth1f2e440 (169.254.183.79).
    ** Ignoring requests on veth1f2e440.  If this is not what
       you want, please write a subnet declaration
       in your dhcpd.conf file for the network segment
       to which interface veth1f2e440 is attached. **

    No subnet declaration for docker0 (172.17.0.1).
    ** Ignoring requests on docker0.  If this is not what
       you want, please write a subnet declaration
       in your dhcpd.conf file for the network segment
       to which interface docker0 is attached. **
    
    No subnet declaration for hassio (172.30.32.1).
    ** Ignoring requests on hassio.  If this is not what
       you want, please write a subnet declaration
       in your dhcpd.conf file for the network segment
       to which interface hassio is attached. **
    
    Listening on LPF/eth0/dc:a6:32:52:60:XX/192.168.1.0/24
    Sending on   LPF/eth0/dc:a6:32:52:60:XX/192.168.1.0/24
    Sending on   Socket/fallback/fallback-net
    Server starting service.

**Comment by nofuturekid** [comment]
Hmm WebGUI now also states it's running.

**Comment by djaydev** [comment]
It looks like it started based on that log info, so are you saying it's not.....

Just saw your reply, congrats!

**Comment by nofuturekid** [comment]
But still no go with the WebGUI in regards of stop/restart...

**Comment by nofuturekid** [comment]
If I use the WebGUI to stop/start/restart the DHCP server (ie. config change) there are error messages in the container logs.

    POST /dhcp_start_stop_restart 127 32.244 ms - 112
    /bin/sh: /usr/sbin/service: not found

And the config change is not applied to the DHCP because it's not restarting.

**Comment by djaydev** [comment]
On the GUI's start/stop/restart feature.  
The original author of glass-isc-dhcp wrote it to work with an init system compatible with Debian or Redhat based distros.  This docker uses alpine linux (for size and speed) so it doesn't understand the commands glass-isc-dhcp uses to start/stop/restart.  

You can view the javascript from the original project below.  If you or someone you know understands javascript and how to rewrite those lines to work with alpine docker I will gladly accept and test any pull request.

https://github.com/Akkadius/glass-isc-dhcp/blob/master/routes/dhcp_start_stop_restart.js

**Comment by nofuturekid** [comment]
Hmm, for sure it's nothing which will be fixed in minutes.
I will have a deeper look another day.

Guess for now this should be closed. And many thanks for your effort and support.

**Comment by nofuturekid** [comment]
Had a glimpse, I guess a small shell script, which you could integrate in your image and put it in "/usr/sbin/service" should do.

I will provide one, maybe tomorrow.

**Comment by djaydev** [comment]
That sounds great!  I will add it to the repo, build and test the docker image

**Comment by nofuturekid** [comment]
[service.zip](https://github.com/djaydev/docker-glass-isc-dhcp/files/4143295/service.zip)

Put the file from inside this ZIP to "/usr/sbin" and make it executable.
Also change the "startapparm.sh" to not call the dhcp directly but instead run "/usr/sbin/service isc-dhcp-server start".

This is very hacky, but at least for ARM it will work and I was able to start/stop the DHCP server via webinterface. (Restart is not working, don't know why)

**Comment by nofuturekid** [comment]
My watchtower catched your new image version, but now I get:

`standard_init_linux.go:211: exec user process caused "exec format error"`

I fetch with the TAG: latest...

**Comment by djaydev** [comment]
the armv7 image hasn't finished building yet.  i'll comment here once they're all done

**Comment by nofuturekid** [comment]
Ahh, fine. Meanwhile I found a little bug in the "service" - if the container is restarted the DHCP will not come up again, because of the leftover PID file in "/run/dhcp/".

I have a fixed version of the script attached.
[service.zip](https://github.com/djaydev/docker-glass-isc-dhcp/files/4143339/service.zip)

**Comment by nofuturekid** [comment]
I hope now to have it in working condition.

**Comment by djaydev** [comment]
updated and restarted docker builds, should be done within the hour

**Comment by nofuturekid** [comment]
Thumbs up! Thanks for being so responsive. I appreciate your work.

**Comment by djaydev** [comment]
the armv7 image has finished and ready for testing

**Comment by nofuturekid** [comment]
Already pulled by watchtower and works as expected.
Now I'm able to stop/start from WebUI and also if the container get's restarted automatically it comes up.

So problem solved.

**Comment by djaydev** [comment]
Thank you for your contribution
